apiVersion: apps/v1
kind: Deployment
metadata:
  name: aichatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aichatbot
  template:
    metadata:
      labels:
        app: aichatbot
    spec:
      containers:
      - name: aichatbot
        image: gcr.io/ann-project-390401/aichatbot:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "2Gi"
            cpu: "500m"
          requests:
            memory: "1Gi"
            cpu: "250m"