apiVersion: apps/v1
kind: Deployment
metadata:
  name: aichatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aichatbot
  template:
    metadata:
      labels:
        app: aichatbot
    spec:
      containers:
      - name: aichatbot
        image: asia-east1-docker.pkg.dev/ann-project-390401/aichatbot:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "10Mi"
            cpu: "10m"
          requests:
            memory: "5Mi"
            cpu: "5m"