name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{secrets.GCP_PROJECT_ID}}
        service_account_key: ${{secrets.GCP_SA_KEY}}
        export_default_credentials: true
    
    - name: Set up Kubernetes
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{secrets.GKE_CLUSTER_NAME}}
        location: ${{secrets.GKE_CLUSTER_LOCATION}}
    
    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml
